accounts/urls.py
from django.urls import re_path
from . import views
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete
)
app_name = 'accounts'

urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    re_path(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^profile/$', views.view_profile, name='view_profile'),
    re_path(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    re_path(r'^password/$', views.change_password, name='change_password'),

    re_path(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect':
    'accounts:password_reset_done', 'email_template_name' : 'accounts/reset_password_email.html'},
    name='reset_password'),

    re_path(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
    name='password_reset_done'),

    re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
    {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'},
    name='password_reset_confirm'),

    re_path(r'^reset-password/complete/$', password_reset_complete, {'template_name': 'accounts/reset_password_complete.html'},
    name='password_reset_complete'),

]

tutorial/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from tutorial import views

urlpatterns = [
    re_path(r'^$', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)

    def __str__(self):
        return '%s' % (self.user.username)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
)
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

#start views here

#Home
@login_required
def home(request):
    numbers = [1,2,3,4,5]
    name = "John Doe"
    args = {'myName': name, 'numbers': numbers}

    return render(request, 'accounts/home.html', args)

#Register
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts')
    else:
        form = RegistrationForm()
    return render(request, 'accounts/reg_form.html', {'form' : form})

#View Profile
@login_required
def view_profile(request):
    args = {'user':request.user}
    return render(request, 'accounts/profile.html', args)

#Edit Profile
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
    else:
        form = EditProfileForm(instance=request.user)
    return render(request, 'accounts/edit_profile.html', {'form' : form})

#Change Password
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user=form.user)
            return redirect('/accounts/profile')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'accounts/change_password.html', {'form' : form})

tutorial/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/accounts/login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Change Password</title>
{% endblock %}

{% block body %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}

<h1>Home</h1>

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<h1>home</h1>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Welcome</h1>
        <p>You can login here:</p>
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Login</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Logged out</h1>
        <p>You have logged out</p>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}

<div class="container">
    <h1>Profile</h1>

    <p>Username: {{ user }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <br>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>

</div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Register</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Password Reset</h1>
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>

        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Reset my password</button>
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Password reset complete</h1>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <p><a href="{% url 'accounts:login' %}">Log in</a></p>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Enter new password</h1>
        <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Reset my password</button>
        </form>

    </div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <h1>Password reset sent</h1>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
        <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
    </div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        {%block head%}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>

    <br/>
    <div class="container">
     <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'accounts:home' %}">Farmplan</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'accounts:login' %}">Farmplan</a>
            {% endif %}
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:home' %}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:register' %}">Register</a></li>
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    </div>

    {%block body%}
     <h1>Base</h1>
    {% endblock %}
    </body>
</html>